### ISSUE TITLE
Connected state not reflected correctly

### ISSUE THREAD

**Issue by thibmaek** [cmroche/OctoPrint-HomeAssistant#33]
<img width="440" alt="image" src="https://user-images.githubusercontent.com/6213695/90989410-e1d7e180-e599-11ea-911a-20e66f557975.png">

<img width="330" alt="image" src="https://user-images.githubusercontent.com/6213695/90989418-ebf9e000-e599-11ea-920f-99b2ed92ba01.png">

When I turn off printer the MQTT event for connection state is not reflecting correctly. Printer disconnects in Octoprint, but stays at the connected state in the MQTT device.

The printing state updates with the expected error message though, but I can't use this in automations:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/6213695/90989462-34b19900-e59a-11ea-9754-b69628d06a81.png">

**Comment by cmroche** [comment]
Thanks for the report, I think I've seen this now that you mention it, so I will look into it this weekend.

**Comment by cmroche** [comment]
Release 2.1.4 should fix this once available to you.

**Comment by thibmaek** [comment]
With the latest version this is still not working correctly for me
![Screenshot 2020-09-13 at 20 01 56](https://user-images.githubusercontent.com/6213695/93025192-3bad5380-f5fc-11ea-9be0-2eff69d15cea.png)

**Comment by cmroche** [comment]
Click **MQTT INFO** and show me the recent messages received for this sensor please. This is what I am looking for:

![image](https://user-images.githubusercontent.com/1007595/93029783-cdf92b80-f5eb-11ea-836f-b61301e95d67.png)

**Comment by thibmaek** [comment]
Seems like the offline event is coming in properly but not changing the binary sensor

<img width="392" alt="Screenshot 2020-09-15 at 19 53 48" src="https://user-images.githubusercontent.com/6213695/93246569-43503200-f78d-11ea-9380-533b5b05aedd.png">

![Uploading Screenshot 2020-09-15 at 19.54.07.png…]()

**Comment by cmroche** [comment]
Oh, looking back at the screenshot you sent the "Connected" sensor says "Connected". This is the correct state. The sensor with the error message is just a generic sensor covering all events that are emitted from OctoPrint, since this happens across many topics in MQTT and not just a single topic that one you see here is the last one it received.

I included this general event sensor in case people wanted to capture something like ZChanged event, I wouldn't rely on it for anything persistent though, it will not be usefull as a general purpose status report.

**Comment by thibmaek** [comment]
Seems like my second screenshot didn't come through. Note how the event for offline & disconnected is being sent for `sensor.octoprint_last_event` at topic `octoprint/event/+`:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/6213695/93494896-d4e6ad80-f90d-11ea-8343-c59ebf6b16be.png">

But `binary_sensor.octoprint_connected` at topic `octoprint/event/Connected` does not reflect this change

<img width="816" alt="image" src="https://user-images.githubusercontent.com/6213695/93495044-fc3d7a80-f90d-11ea-8fba-5711a0b99873.png">

**Comment by thibmaek** [comment]
I think in `def _on_mqtt_message()` you would need to check for the topic `octoprint/event/+` if `state_string` in the message is equal to `offline` and then update the Connected sensor

**Comment by cmroche** [comment]
@thibmaek Unfortunately it's not so simple.

Because of the splitting of connected and disconnected into separate topics, I suspect that the sensor is just flat out broken. I'm not sure how to fix it properly yet, I'll need to look into this more.
